Lle_media_file_upload:
    path:     /file/upload/{id}
    defaults: { _controller: LleMediaBundle:Default:fileUpload }
    requirements:
        _method:  POST

Lle_media_folder_action:
    path:     /folder
    defaults: { _controller: LleMediaBundle:Default:folder }
    requirements:
        _method:  POST
Lle_media_delete_folder:
    path:     /deleteFolder/{id}
    defaults: { _controller: LleMediaBundle:Default:deleteFolder }
    requirements:
        _method:  POST
Lle_media_delete_file:
    path:     /deleteFile/{id}
    defaults: { _controller: LleMediaBundle:Default:deleteFile }
    requirements:
        _method:  POST

Lle_media_download_file:
    path:     /downloadFile/{id}
    defaults: { _controller: LleMediaBundle:Default:downloadFile }

Lle_media_edit_file:
    path:     /editFile/{id}
    defaults: { _controller: LleMediaBundle:Default:editFile }
Lle_media_update_file:
    path:     /updateFile/{id}
    defaults: { _controller: LleMediaBundle:Default:updateFile }

Lle_media_homepage:
    path:     /{id}
    defaults: { _controller: LleMediaBundle:Default:getFolder , id:0 }