services:

    _defaults:
        autowire: true
        public: false
        autoconfigure: true


    Lle\MediaBundle\Service\:
        resource: '../../Service'

    Lle\MediaBundle\Command\ReaderMediaCommand:
        arguments: ["@doctrine.orm.entity_manager"]

